### ISSUE TITLE
when in quest list page - click on enter - it will go to new quest page

### ISSUE THREAD

**Issue by zero10xy** [BetHero-pro/BetHero#7]
![Image](https://github.com/BetHero-pro/BetHero/assets/9776377/3830f1f9-85b6-4a34-8eaf-80a17c15cf79)

click enter

![Image](https://github.com/BetHero-pro/BetHero/assets/9776377/61cad128-6ca0-4d1c-9427-2260213b87db)

**Comment by zero10xy** [comment]
better
now when i click enter i go into write quetst page - good
but there are some bug in that
if in the list there is some task, and i click enter, it will show in the writing quest the text of the last task in the list
showing screenshot:

![Image](https://github.com/BetHero-pro/BetHero/assets/9776377/5571c182-f1d4-40bb-bc64-c6fa2fd393b4)

when i click enter - it need to show empty field so i can write new text of the quest - it dont need to show the last quest text already there

**Comment by zero10xy** [comment]
how its going?

**Comment by zero10xy** [comment]
update on it?

**Comment by zero10xy** [comment]
@jay0x5 any update on that?

**Comment by jay0x5** [comment]
The issue will be soon conveyed to available developer

**Comment by zero10xy** [comment]
> 

ok

**Comment by nooandpro77** [comment]
![image](https://github.com/BetHero-pro/BetHero/assets/64268601/943ee035-fe54-43d4-b03b-b00808bcdf78)

![image](https://github.com/BetHero-pro/BetHero/assets/64268601/9d232439-03d8-4e4c-9e19-a54d698b26eb)

![image](https://github.com/BetHero-pro/BetHero/assets/64268601/85923089-d787-4798-b75b-a9d86f904ee0)


i think this issue is already resolved so we should close it

**Comment by nooandpro77** [comment]
done too
